var nm1 = ["Ace","Aetherwing","Agamemnon","Apollo","Arcadia","Atlas","Azrael","Benediction","Blackjack","Bliss","Calypso","Ceres","Charity","Cloudsong","Curio","Curiosity","Dawn","Dominus","Duchess Emily","Elysium","Epoch","Glee","Grace","Hailstone","Helios","Heritage","Honor","Horizon","Invincible","Joy","Jupiter","Justice","Lady Liberty","Luminus","Memento","Mercy","Nemo","Neptune","Nightmare","Olympus","Orbit","Pandora","Patience","Prometheus","Proximus","Rara Avis","Red Rose","Saturn","Scarlet","Star Gazer","Starlight","Stormlight","Summersong","Sweetwater","The Albatross","The Allure","The Amaranth","The Ambassador","The Andromeda","The Animus","The Anomaly","The Artifact","The Aspect","The Aura","The Aurora","The Azure","The Babylon","The Baron","The Bastion","The Behemoth","The Borealis","The Buccaneer","The Cardinal","The Clemency","The Climax","The Condor","The Conundrum","The Courtesy","The Crown","The Crusader","The Dauntless","The Daydream","The Decadence","The Delight","The Destiny","The Dragonfly","The Dreadnought","The Duchess","The Duke","The Eagle","The Eclipse","The Ecstasy","The Endeavor","The Endurance","The Enigma","The Enterprise","The Equinox","The Euphoria","The Excelsior","The Falcon","The Felicity","The Figment","The Freebird","The Frigate","The Galaxy","The Genius","The Gryphon","The Halcyon","The Happening","The Harlot","The Harmony","The Heirloom","The Herald","The Heritage","The Hummingbird","The Icarus","The Indulgence","The Intrepid","The Javelin","The Jubilation","The Jubilee","The Juggernaut","The Legacy","The Leviathan","The Lullaby","The Macaw","The Maiden","The Majesty","The Masquerade","The Mayflower","The Miracle","The Mirth","The Nautilus","The Nemesis","The Night Lady","The Nightingale","The Nightwish","The Nirvana","The Obelisk","The Odyssey","The Oracle","The Orion","The Outlook","The Parable","The Paradox","The Paragon","The Pathfinder","The Pegasus","The Pelican","The Phantasm","The Phenomenon","The Phoenix","The Pinnacle","The Pioneer","The Prism","The Prodigy","The Prosperity","The Providence","The Renegade","The Repose","The Reticence","The Reticent","The Revelation","The Revenant","The Riddle","The Rose Blossom","The Sanctity","The Saturninity","The Sentinel","The Serenity","The Skyshadow","The Skywarden","The Solitude","The Solstice","The Spectacle","The Spire","The Stormherald","The Summit","The Sunbird","The Surge","The Tempest","The Titan","The Tribute","The Triumph","The Utopia","The Valhalla","The Valiant","The Valkyrie","The Vestige","The Vision","The Warden","The Wayfarer","The Zephyr","The Zodiac","Tranquillity","Triton","Wanderlust","Wishmaster","Zenith","Zion"];
var nm2 = ["Adventurous","Agile","Ample","Anchored","Ancient","Angelic","Angry","Antique","Arctic","Austere","Azure","Bare","Barren","Beloved","Big","Bitter","Black","Blank","Blind","Blond","Blushing","Bold","Brave","Bright","Brilliant","Bronze","Brown","Burly","Canine","Capital","Cold","Crafty","Crazy","Crimson","Crooked","Crown","Curvy","Dapper","Daring","Darling","Dazzling","Dear","Defiant","Delayed","Devoted","Diligent","Discrete","Distant","Eager","Ebon","Elder","Elegant","Emerald","Enchanted","Enlightened","Euphoric","Exalted","Faithful","False","Fancy","Fantastic","Fearless","Feisty","Feline","First","Forsaken","Gentle","Giant","Glass","Glorious","Golden","Graceful","Grand","Great","Grim","Happy","Heavy","High","Hollow","Honest","Humble","Humming","Husky","Idle","Infamous","Intrepid","Ivory","Jagged","Last","Little","Lone","Lonely","Lost","Loyal","Lucky","Majestic","Merry","Nimble","Odd","Old","Pale","Plump","Precious","Prime","Pure","Quiet","Rapid","Red","Round","Royal","Scented","Serene","Silent","Silver","Skinny","Slim","Soft","Striped","Swift","Tender","Tiny","Vibrant","Violet","Warm","White","Wicked"];
var nm3 = ["Allure","Ambassador","Ambience","Amity","Apex","Aspect","Aura","Aurora","Baron","Baroness","Bastion","Behemoth","Bolt","Bounty","Buccaneer","Bullet","Bulwark","Cardinal","Champion","Charity","Citadel","Clemency","Climax","Cloud","Concord","Condor","Countess","Crown","Crusader","Crux","Dame","Dawn","Daydream","Delight","Destiny","Dominion","Dragonfly","Dream","Duchess","Duke","Eagle","Eclipse","Emissary","Endeavor","Enigma","Enterprise","Envoy","Falcon","Felicity","Fortress","Fortune","Frigate","Genesis","Grace","Gryphon","Harmony","Heirloom","Herald","Heritage","Homage","Honor","Horizon","Hummingbird","Javelin","Jewel","Joy","Justice","Lady","Legacy","Lord","Maiden","Majesty","Marvel","Matron","Mercy","Miracle","Mirage","Mistress","Monarch","Monument","Muse","Needle","Nemesis","Nightingale","Obelisk","Odyssey","Omen","Oracle","Parable","Paradox","Paragon","Parapet","Pegasus","Phantasm","Phenomenon","Phoenix","Pinnacle","Pioneer","Prestige","Princess","Prodigy","Prophecy","Quest","Relic","Renegade","Revenant","Riddle","Sentinel","Sentry","Serenity","Shade","Shadow","Shroud","Solstice","Spectacle","Specter","Summit","Surge","Tempest","Titan","Tribute","Triumph","Unity","Valkyrie","Vertex","Vestige","Vision","Voyage","Warden","Wish","Zenith","Zodiac"];
var nm4 = ["Écarlate","Élysée","Étoile","Ace","Agamemnon","Alcyon","Apollon","Arcadie","Atlas","Azrael","Babylone","Borealis","Calypso","Cauchemar","Ceres","Chérie","Curio","Curiosité","Dominus","Dreadnought","Duchesse","Excelsior","Gaieté","Grâce","Grêle","Hélios","Héritage","Honneur","Icarus","Invincible","Joie","Jupiter","Justice","Liberté","Lumière","Luminus","Mémento","Matraque","Merveille","Nemo","Neptune","Nirvana","Nuage","Olympe","Orbite","Orion","Pandora","Patience","Patrimoine","Prométhée","Proximus","Répit","Rêve","Rêverie","Rara Avis","Rose Rouge","Saturne","Sion","Stargazer","Valhalla","l'Éclaireur","l'Éclipse","l'Énigme","l'Époque","l'Équinoxe","l'Été","l'Événement","l'Aigle","l'Albatross","l'Amarante","l'Ambassadeur","l'Andromède","l'Animus","l'Anomalie","l'Apogée","l'Ara","l'Artefact","l'Aspect","l'Attrait","l'Aube","l'Aura","l'Aurore","l'Aventure","l'Azur","l'Effort","l'Endurance","l'Entreprise","l'Euphorie","l'Extase","l'Héritage","l'Harmonie","l'Hommage","l'Indulgence","l'Initiative","l'Intrépide","l'Obélisque","l'Odyssée","l'Oiseau Libre","l'Ombre","l'Oracle","l'Utopie","la Bénédiction","la Berceuse","la Bougeotte","la Charité","la Clémence","la Couronne","la Courtisane","la Courtoisie","la Création","la Décadence","la Dame de la Nuit","la Demoiselle","la Duchesse","la Félicité","la Flèche","la Fleur de Rose","la Frégate","la Galaxie","la Grandeur","la Javeline","la Joie","la Jubilation","la Libellule","la Majesté","la Mascarade","la Merveille","la Némésis","la Nuit","la Parabole","la Perspective","la Prévoyance","la Prospérité","la Providence","la Réticence","la Révélation","la Rêverie","la Sérénité","la Sainteté","la Saturnité","la Sentinelle","la Solitude","la Tempête","la Tranquillité","la Valkyrie","la Vierge","la Vision","la Vue","le Baron","le Bastion","le Boucanier","le Brave","le Cardinal","le Climax","le Colibri","le Condor","le Croisé","le Délice","le Désir","le Destin","le Duc","le Fantasme","le Faucon","le Génie","le Gardien","le Griffon","le Héraut","le Javelot","le Jubilé","le Léviathan","le Mastodonte","le Miracle","le Monstre","le Mystère","le Nautile","le Pégase","le Pélican","le Paradoxe","le Parangon","le Phénix","le Phénomène","le Pic","le Pionnier","le Prisme","le Prodige","le Renégat","le Repos","le Revenant","le Rossignol","le Sommet","le Souhait","le Spectacle","le Titan","le Triomphe","le Triton","le Vestige","le Voyageur","le Zénith","le Zéphyr","le Zodiaque"];
var nm5 = ["l'Éclipse","l'Énigme","l'Aiguille","l'Allure","l'Ambassadrice","l'Ambiance","l'Amitié","l'Aube","l'Aura","l'Aurore","la Baronne","la Championne","la Chance","la Charité","la Cime","la Citadelle","la Clémence","la Comtesse","la Concorde","la Couronne","la Dame","la Douceur","la Duchesse","l'Entreprise","l'Envie","la Félicité","la Forteresse","la Fortune","la Frégate","la Genèse","la Grâce","l'Harmonie","l'Indulgence","la Javeline","la Joie","la Joliesse","la Justice","la Libellule","la Maîtresse","la Majesté","la Marveille","la Matrone","la Merveille","la Muse","la Némésis","l'Odyssée","l'Ombre","la Parabole","la Poursuite","la Prime","la Princesse","la Prophétie","la Quête","la Rêverie","la Relique","la Sérénité","la Sentinelle","la Songerie","la Tempête","la Tranquillité","l'Unité","la Valkyrie","la Victoire","la Vierge","la Vision","la Vue","l'Émissaire","l'Aigle","l'Ambassadeur","l'Aspect","le Baron","le Bastion","le Bijou","le Boucanier","le Cardinal","le Champion","le Climax","le Colibri","le Condor","le Croisé","le Délice","le Désir","le Destin","le Duc","l'Effort","l'Envoyé","le Fantasme","le Faucon","le Gardien","le Griffon","le Héraut","l'Héritage","l'Hommage","l'Honneur","l'Horizon","le Javelot","le Juge","le Maître","le Miracle","le Mirage","le Monarque","le Monstre","le Monument","le Mystère","le Nuage","l'Obélisque","l'Oracle","le Pégase","le Paradoxe","le Parangon","le Parapet","le Phénix","le Phénomène","le Pionnier","le Présage","le Prestige","le Prince","le Prodige","le Rêve","le Rempart","le Renégat","le Revenant","le Rossignol","le Solstice","le Sommet","le Sort","le Souhait","le Spectacle","le Spectre","le Titan","le Tribut","le Triomphe","le Vestige","le Voile","le Voyage","le Zénith","le Zodiaque"];
var nm6a = ["Éblouissant","Éclairé","Éclatant","Élégant","Émeraude","Étonnant","Étrange","Abandonné","Adoré","Agile","Ainé","Ambitieux","Ancien","Ancré","Angélique","Antique","Arctique","Astucieux","Audacieux","Auguste","Austère","Aventureux","Aveugle","Avide","Azuré","Bien-Aimé","Blond","Brave","Brillant","Brun","Canin","Chéri","Chanceux","Costaud","Courageux","Courbé","Cramoisi","Creux","Cruel","Déchiqueté","Délaissé","Désireux","Dévoué","Différé","Diligent","Dingue","Discret","Dodu","Doux","Enchanté","Euphorique","Exalté","Excellent","Fâché","Félin","Fantaisie","Fantastique","Fidèle","Formidable","Fou","Froid","Furieux","Géant","Glorieux","Gracieux","Grandiose","Hardi","Heureux","Honnête","Humble","Impitoyable","Incarnat","Indifférent","Infâme","Intrépide","Joyeux","Leste","Loin","Luisant","Méchant","Macabre","Magnifique","Maigre","Majestueux","Marron","Mince","Miniscule","Modeste","Obscur","Pâle","Paisible","Parfumé","Perdu","Pimpant","Précieux","Provocant","Pur","Rapide","Rayé","Rayonnant","Rond","Rouge","Rougissant","Royal","Rusé","Serein","Silencieux","Sincère","Sinistre","Solitaire","Sombre","Tranquille","Vermeil","Vibrant","Vide","Violet","Vivant","Voilé","d'Ébène","d'Argent","d'Ivoire","d'Or","de Bourdonnement","de Bronze","de Défi","de Luxe","de Verre","de la Couronne","en Verre"];
var nm6b = ["Éblouissante","Éclairée","Éclatante","Élégante","Émeraude","Étonnante","Étrange","Abandonnée","Adorée","Agile","Ainée","Ambitieuse","Ancienne","Ancrée","Angélique","Antique","Arctique","Astucieuse","Audacieuse","Auguste","Austère","Aventureuse","Aveugle","Avide","Azurée","Bien-Aimée","Blonde","Brave","Brillante","Brune","Canine","Chérie","Chanceuse","Costaude","Courageuse","Courbée","Cramoisie","Creuse","Cruelle","Déchiquetée","Délaissée","Désireuse","Dévouée","Différée","Diligente","Dingue","Discrète","Dodue","Douce","Enchantée","Euphorique","Exaltée","Excellente","Fâchée","Féline","Fantaisie","Fantastique","Fidèle","Formidable","Folle","Froide","Furieuse","Géante","Glorieuse","Gracieuse","Grandiose","Hardie","Heureuse","Honnête","Humble","Impitoyable","Incarnat","Indifférente","Infâme","Intrépide","Joyeuse","Leste","Loine","Luisante","Méchante","Macabre","Magnifique","Maigre","Majestueuse","Marron","Mince","Miniscule","Modeste","Obscure","Pâle","Paisible","Parfumée","Perdue","Pimpante","Précieuse","Provocante","Pure","Rapide","Rayée","Rayonnante","Ronde","Rouge","Rougissante","Royale","Rusée","Sereine","Silencieuse","Sincère","Sinistre","Solitaire","Sombre","Tranquille","Vermeille","Vibrante","Vide","Violette","Vivante","Voilée"];
var br = "";

function nameGen(type){
	var tp = type;
	var element = document.createElement("div");
	element.setAttribute("id", "result");
	
	for(i = 0; i < 10; i++){
		if(tp === 1){
			if(i < 5){
				rnd = Math.random() * nm4.length | 0;
				names = nm4[rnd];
			}else{
				rnd = Math.random() * nm5.length | 0;
				rnd2 = Math.random() * nm6a.length | 0;
				if(rnd < 66 && rnd2 < 118){
					names = nm5[rnd] + " " +  nm6b[rnd2];
				}else{
					names = nm5[rnd] + " " +  nm6a[rnd2];
				}
			}
		}else{
			if(i < 5){
				rnd = Math.random() * nm1.length | 0;
				names = nm1[rnd];
			}else{
				rnd = Math.random() * nm2.length | 0;
				rnd2 = Math.random() * nm3.length | 0;
				names = nm2[rnd] + " " +  nm3[rnd2];
			}
		}
		br = document.createElement('br');	
		element.appendChild(document.createTextNode(names));
		element.appendChild(br);
	}
	if(document.getElementById("result")){
		document.getElementById("placeholder").removeChild(document.getElementById("result"));
	}		
	document.getElementById("placeholder").appendChild(element);
}