var nm1 = ["Aggressive","Agitated","Agony","Aggressive","Ancient","Angel","Angry","Animated","Anxious","Arachnid","Autumn","Avian","Bacterial","Banshee","Beer","Black","Boar","Brain","Brittle","Buzzing","Canine","Cat","Cave","Chicken","Chilling","Cold","Collapsing","Contagious","Cow","Crazy","Creeping","Crippling","Crumbling","Crying","Crystal","Curable","Deadly","Death's","Deathbell","Decaying","Delirious","Demon","Desert","Desolation","Deteriorating","Devil's","Dog","Dragon","Dream","Dreaming","Duck","Dwarf","Dying","Elastic","Elephant","Enlarged","Ethereal","Exhausting","Explosive","Fading","Failing","Fall","Falling","Fatal","Feline","Fickle","Fiery","Fisherman's","Flower","Forceful","Forest","Frenzied","Frost","Frozen","Ghastly","Ghost","Goblin","Golden","Goose","Grave","Green","Growing","Guttural","Happy","Harmless","Heaven's","Hell","Hellish","Hiccup","Hopeless","Horse","Hostile","Hot","Humming","Hyper","Icy","Immobilizing","Impossible","Incurable","Intense","Iron","Ironbark","Island","Jumping","Jungle","King's","Lady","Laughing","Lifeless","Limp","Lion","Lizard","Man","Marsh","Memory","Mild","Milk","Mortal","Mountain","Mouse","Necrotic","Nervous","Numb","Numbing","Ogre","Orange","Pale","Paralyzing","Peaceful","Permanent","Pestilent","Petrifying","Phantom","Pig","Pink","Pygmy","Queen's","Quiet","Quivering","Rabbit","Rabid","Rasping","Rat","Red","Restless","Rickety","Rock","Rodent","Rooster","Rotting","Running","Sage","Screaming","Sedated","Serpent","Shadow","Shaking","Shaky","Sheep","Shivering","Shriveling","Silent","Silver","Sinister","Sleep","Smiling","Snake","Sniffling","Soft","Soul","Spastic","Spider","Spine","Spirit","Spring","Steel","Sterile","Stiff","Stiffening","Stimulated","Stinging","Stomach","Stranger's","Stressed","Stressful","Stunned","Summer","Swamp","Swine","Temporary","Terrifying","Thorny","Ticklish","Tiring","Tomb","Tranquil","Tree","Trembling","Trivial","Twitching","Ugly","Undead","Vein","Violet","Volatile","Warping","Water","Weak","Weakening","Whispering","Wicked","Wild","Winter","Wired","Witch","Withering","Wizard","Wolf","Wooden","Worn","Wraith","Yellow","Zombie"];
var nm2 = ["Ache","Aching","Acne","Allergy","Amnesia","Anemia","Anthrax","Anxiety","Arthritis","Asthma","Baldness","Blight","Blindness","Blisters","Body","Bones","Bronchitis","Cancer","Cannibalism","Chills","Chlamydia","Cholera","Cold","Cough","Cramps","Deafness","Death","Decay","Deficiency","Dehydration","Delirium","Delusion","Delusions","Depression","Diphtheria","Disease","Dysfunctions","Ears","Ebola","Epilepsy","Euphoria","Eye","Eyes","Fatigue","Feet","Fever","Finger","Flu","Foot","Gangrene","Gonorrhea","Hallucinations","Hands","Head","Heart","Hepatitis","Herpes","Illness","Infection","Infertility","Inflammation","Influenza","Insanity","Insomnia","Intolerance","Irritation","Leprosy","Lupus","Malaria","Measles","Meningitis","Migraine","Mouth","Mutation","Nausea","Nose","Panic","Paralysis","Paranoia","Parasite","Plague","Pneumonia","Poisoning","Pox","Rabies","Rage","Rash","Salmonella","Scarring","Schizophrenia","Scurvy","Shock","Skin","Sleep Disorder","Sneeze","Soreness","Sores","Spasms","Stiffness","Stomach","Swelling","Syndrome","Syphilis","Tetanus","Throat","Tongue","Tumor","Ulcers","Vampirism","Virus","Warts"];
var nm3 = ["l'Épilepsie","l'Acné","l'Allergie","l'Amnésie","l'Anémie","l'Anthropophagie","l'Anxiété","l'Arthrite","la Blennorragie","la Bouche","la Bronchite","la Cécité","la Calvitie","la Cerence","la Chlamydia","la Contagion","la Corruption","la Crise","la Déficience","la Démence","la Dépression","la Déshydration","la Diphtérie","la Douleur","l'Enflure","l'Euphorie","la Fatigue","la Fièvre","la Folie","la Gangrène","la Gorge","la Grippe","l'Hépatite","l'Illusion","l'Infection","l'Infertilité","l'Inflammation","l'Insanité","l'Insomnie","l'Insuffisance","l'Intolérance","l'Intoxication","l'Irritation","la Lèpre","la Langue","la Méningite","la Main","la Maladie","la Malaria","la Migraine","la Mort","la Mutation","la Nausée","la Panique","la Paralysie","la Paranoïa","la Parasite","la Peau","la Peste","la Plaie","la Pneumonie","la Pourriture","la Rage","la Rigidité","la Rougeole","la Salmonelle","la Scarification","la Schizophrénie","la Stérilité","la Surdité","la Syphilis","la Tête","la Toux","la Tumeur","la Vérole","la Variole","les Ampoules","les Cloques","les Hallucinations","les Illusions","les Mains","les Oreilles","les Plaies","les Verrues","l'Éternuement","l'Œil","l'Anthrax","l'Asthme","le Cœur","le Cancer","le Cannibalisme","le Choc","le Choléra","le Corps","le Délire","le Doigt","le Dysfonctionnement","l'Ebola","l'Endolorissement","l'Estomac","le Fléau","le Gonflement","l'Herpès","le Lupus","le Mal","le Nez","le Paludisme","le Pied","le Rhume","le Scorbut","le Spasme","le Syndrome","le Tétanos","l'Ulcère","le Vampirisme","le Virus","les Crampes","les Frissons","les Os","les Pieds","les Spasmes","les Ulcères","les Yeux"];
var nm4a = ["Élastique","Énergique","Épineux","Épuisant","Éteint","Éthéré","Étourdi","Étrange","Affaiblissant","Agité","Agrandi","Agressif","Ancien","Angelique","Animé","Anxieux","Ardent","Argenté","Atroce","Auxiliaire","Aviaire","Bactérien","Blessant","Bourdonnant","Canin","Changeant","Chatouilleux","Chaud","Chuchotant","Cinglant","Contagieux","Courant","Criant","Croissant","Cuisant","Débilitant","Déclinant","Défaillant","Délicat","Délirant","Démoniaque","Désespéré","Détérioré","Diabolique","Doré","Doux","Dur","Engourdi","Engourdissant","Enragé","Explosif","Fâché","Félin","Faible","Farouche","Fatal","Fatigant","Fatigué","Flétri","Fou","Fougueux","Frémissant","Frénétique","Fragile","Froid","Fugace","Furieux","Glacé","Grandissant","Grave","Grimpant","Grinçant","Guérissable","Horrible","Hostile","Hurlant","Immobilisant","Impossible","Inconstant","Incurable","Innocent","Inoffensif","Insignifiant","Intense","Jaune","Joyeux","Livide","Méchant","Méprisant","Malicieux","Maniaque","Moche","Morne","Mort-Vivant","Mortel","Mou","Mourant","Muet","Nécrotique","Néfaste","Naissant","Nerveux","Noir","Nuisible","Orange","Pâle","Pâlissant","Pétrifiant","Paisible","Paralysant","Permanent","Pestilentiel","Pourrissant","Précaire","Puissant","Pygmée","Répugnant","Rêvant","Rachitique","Raide","Raidissant","Rampant","Ratatinant","Remédiable","Riant","Rigide","Rongeur","Rose","Rouge","Sacré","Sage","Sauteur","Sauvage","Serpentin","Silencieux","Sinistre","Sinueux","Souriant","Spasmodique","Spastique","Stérile","Stimulé","Stressé","Stressant","Stupéfié","Temporaire","Tenace","Terrifiant","Tranquille","Tremblant","Tremblotant","Vert","Vibrant","Violent","Violet","Volatil","d'Âme","d'Éléphant","d'Été","d'Étranger","d'Île","d'Acier","d'Agonie","d'Ange","d'Apparition","d'Arachnide","d'Araignée","d'Arbre","d'Argent","d'Automne","d'Eau","d'Enfer","d'Esprit","d'Estomac","d'Hiver","d'Homme","d'Ogre","d'Oie","d'Ombre","d'Or","de Banshee","de Bière","de Bois","de Canard","de Caverne","de Chat","de Cheval","de Chien","de Cochon","de Contractions","de Coq","de Cristal","de Démon","de Désert","de Désolation","de Dame","de Diable","de Dos","de Dragon","de Faiblesse","de Fantôme","de Femme","de Fer","de Fleur","de Floraison","de Forêt","de Froid","de Gauchissement","de Gel","de Gobelin","de Grotte","de Hoquet","de Jungle","de Lézard","de Lait","de Lapin","de Lion","de Loup","de Marais","de Montagne","de Mort","de Mouton","de Nain","de Pêcheur","de Paradis","de Porch","de Poule","de Printemps","de Rêve","de Rat","de Refroidissement","de Reine","de Roc","de Roche","de Roi","de Rongeur","de Sanglier","de Serpent","de Solitude","de Sommeil","de Sorcellerie","de Sorcier","de Souris","de Spectre","de Stress","de Tombe","de Tomber","de Vache","de Zombie","de la Mémoire","de la Tombe","de la Veine","des Veines","du Cerveau","en Baisse","en Décomposition","en Pleur","en Ruine"];
var nm4b = ["Élastique","Énergique","Épineuse","Épuisante","Éteinte","Éthérée","Étourdie","Étrange","Affaiblissante","Agitée","Agrandie","Agressive","Ancienne","Angelique","Animée","Anxieuse","Ardente","Argentée","Atroce","Auxiliaire","Aviaire","Bactérienne","Blessaent","Bourdonnante","Canine","Changeante","Chatouilleuse","Chaude","Chuchotante","Cinglante","Contagieuse","Courante","Criante","Croissante","Cuisante","Débilitante","Déclinante","Défaillante","Délicate","Délirante","Démoniaque","Désespérée","Détériorée","Diabolique","Dorée","Douce","Dure","Engourdie","Engourdissante","Enragée","Explosive","Fâchée","Féline","Faible","Farouche","Fatale","Fatiganet","Fatiguée","Flétrie","Folle","Fougueuse","Frémissante","Frénétique","Fragile","Froide","Fugace","Furieuse","Glacée","Grandissante","Grave","Grimpante","Grinçante","Guérissable","Horrible","Hostile","Hurlante","Immobilisante","Impossible","Inconstante","Incurable","Innocente","Inoffensive","Insignifiante","Intense","Jaune","Joyeuse","Livide","Méchante","Méprisante","Malicieuse","Maniaque","Moche","Morne","Mort-Vivante","Mortelle","Mou","Mourante","Muette","Nécrotique","Néfaste","Naissante","Nerveuse","Noire","Nuisible","Orange","Pâle","Pâlissante","Pétrifiante","Paisible","Paralysante","Permanente","Pestilentielle","Pourrissante","Précaire","Puissante","Pygmée","Répugnante","Rêvante","Rachitique","Raide","Raidissante","Rampante","Ratatinante","Remédiable","Riante","Rigide","Rongeur","Rose","Rouge","Sacrée","Sage","Sauteur","Sauvage","Serpentin","Silencieuse","Sinistre","Sinueuse","Souriante","Spasmodique","Spastique","Stérile","Stimulée","Stressée","Stressante","Stupéfiée","Temporaire","Tenace","Terrifiante","Tranquille","Tremblante","Tremblotante","Verte","Vibrante","Violente","Violette","Volatile","d'Âme","d'Éléphant","d'Été","d'Étranger","d'Île","d'Acier","d'Agonie","d'Ange","d'Apparition","d'Arachnide","d'Araignée","d'Arbre","d'Argent","d'Automne","d'Eau","d'Enfer","d'Esprit","d'Estomac","d'Hiver","d'Homme","d'Ogre","d'Oie","d'Ombre","d'Or","de Banshee","de Bière","de Bois","de Canard","de Caverne","de Chat","de Cheval","de Chien","de Cochon","de Contractions","de Coq","de Cristal","de Démon","de Désert","de Désolation","de Dame","de Diable","de Dos","de Dragon","de Faiblesse","de Fantôme","de Femme","de Fer","de Fleur","de Floraison","de Forêt","de Froid","de Gauchissement","de Gel","de Gobelin","de Grotte","de Hoquet","de Jungle","de Lézard","de Lait","de Lapin","de Lion","de Loup","de Marais","de Montagne","de Mort","de Mouton","de Nain","de Pêcheur","de Paradis","de Porch","de Poule","de Printemps","de Rêve","de Rat","de Refroidissement","de Reine","de Roc","de Roche","de Roi","de Rongeur","de Sanglier","de Serpent","de Solitude","de Sommeil","de Sorcellerie","de Sorcier","de Souris","de Spectre","de Stress","de Tombe","de Tomber","de Vache","de Zombie","de la Mémoire","de la Tombe","de la Veine","des Veines","du Cerveau","en Baisse","en Décomposition","en Pleur","en Ruine"];

function nameGen(type){
	var tp = type;
	var br = "";
	var element = document.createElement("div");
	element.setAttribute("id", "result");
	
	for(i = 0; i < 10; i++){
		if(tp === 1){
			rnd = Math.random() * nm3.length | 0;
			rnd2 = Math.random() * nm4a.length | 0;
			if(rnd < 84){
				if(rnd2 < 156 && rnd > 75){
					plur = nm4b[rnd2].charAt(nm4b[rnd2].length-1);
					if(plur === "s" || plur === "x"){
						names = nm3[rnd] + " " + nm4b[rnd2];
					}else{
						names = nm3[rnd] + " " + nm4b[rnd2] + "s";
					}
				}else{
					names = nm3[rnd] + " " + nm4b[rnd2];
				}
			}else{
				if(rnd2 < 134 && rnd > 115){
					plur = nm4a[rnd2].charAt(nm4a[rnd2].length-1);
					if(plur === "s" || plur === "x"){
						names = nm3[rnd] + " " + nm4a[rnd2];
					}else{
						names = nm3[rnd] + " " + nm4a[rnd2] + "s";
					}
				}else{
					names = nm3[rnd] + " " + nm4a[rnd2];
				}
			}
		}else{
			rnd = Math.random() * nm1.length | 0;
			rnd2 = Math.random() * nm2.length | 0;
			names = nm1[rnd] + " " + nm2[rnd2];
		}
		br = document.createElement('br');	
		element.appendChild(document.createTextNode(names));
		element.appendChild(br);
	}
	if(document.getElementById("result")){
		document.getElementById("placeholder").removeChild(document.getElementById("result"));
	}		
	document.getElementById("placeholder").appendChild(element);
}