var nm1=["","","","c","cr","h","j","k","l","m","n","p","q","qr","r","v","z"];var nm2=["ei","aa","uu","y","a","e","i","o","y","a","e","i","o","y","a","e","i","o","y","a","e","i","o","y","a","e","i","o"];var nm3=["c","cl","d","dd","dh","dr","hm","k","kh","kl","l","ln","lm","lr","ld","lg","ll","m","mn","mr","ml","n","ng","nw","nv","nr","ph","r","rg","rgn","rn","ry","rst","s","sh","sn","sl","ss"];var nm4=["aa","oa","io","iu","a","e","i","o","u","a","e","i","o","u","a","e","i","o","u","a","e","i","o","u"];var nm5=["d","dd","dr","l","ln","lr","ld","lv","lny","m","md","n","nd","nm","nd","r","rn","rl","s","sl","sn","t","v"];var nm6=["","","h","l","m","n","r","s","th"];var nm7=["","","","","","c","ch","chr","d","dh","h","j","n","p","s","t","v","y","z"];var nm8=["ei","ee","a","e","i","o","u","y","a","e","i","o","u","y","a","e","i","o","u","y","a","e","i","o","u","y","a","e","i","o","u","y"];var nm9=["c","ct","d","h","hn","hl","l","ll","lm","ln","m","mn","n","nn","nh","nl","nr","r","rr","rh","rl","s","sm","sp","sh","sn","tsh","th"];var nm10=["ia","ei","io","uo","y","a","e","i","o","u","y","a","e","i","o","u","y","a","e","i","o","u","y","a","e","i","o","u"];var nm11=["d","h","l","ll","lw","lv","n","nd","nv","nn","nw","r","rd","rm","rn","rw","rl","s","sl","sr","ss"];var nm12=["","","","","","h","ht","l","n","r","s","sh","th"];var br="";function nameGen(type){var tp=type;$('#placeholder').css('textTransform','capitalize');var element=document.createElement("div");element.setAttribute("id","result");for(i=0;i<10;i++){if(tp===1){nameFem();while(nMs===""){nameFem();}}else{nameMas();while(nMs===""){nameMas();}}
names=nMs;br=document.createElement('br');element.appendChild(document.createTextNode(nMs));element.appendChild(br);}
if(document.getElementById("result")){document.getElementById("placeholder").removeChild(document.getElementById("result"));}
document.getElementById("placeholder").appendChild(element);}
function nameMas(){nTp=Math.random()*6|0;rnd=Math.random()*nm1.length|0;rnd2=Math.random()*nm2.length|0;rnd3=Math.random()*nm3.length|0;rnd4=Math.random()*nm4.length|0;rnd5=Math.random()*nm6.length|0;if(nTp<3){while(nm3[rnd3]===nm6[rnd5]||nm3[rnd3]===nm1[rnd]){rnd3=Math.random()*nm3.length|0;}
nMs=nm1[rnd]+nm2[rnd2]+nm3[rnd3]+nm4[rnd4]+nm6[rnd5];}else{rnd6=Math.random()*nm5.length|0;rnd7=Math.random()*nm2.length|0;while(nm6[rnd5]===nm5[rnd6]||nm5[rnd6]===nm3[rnd3]){rnd6=Math.random()*nm5.length|0;}
if(nTp<5){nMs=nm1[rnd]+nm2[rnd2]+nm3[rnd3]+nm2[rnd7]+nm5[rnd6]+nm4[rnd4]+nm6[rnd5];}else{rnd8=Math.random()*nm5.length|0;rnd9=Math.random()*nm2.length|0;while(nm6[rnd5]===nm5[rnd8]||nm5[rnd8]===nm5[rnd6]){rnd6=Math.random()*nm5.length|0;}
nMs=nm1[rnd]+nm2[rnd2]+nm3[rnd3]+nm2[rnd7]+nm5[rnd6]+nm2[rnd9]+nm5[rnd8]+nm4[rnd4]+nm6[rnd5];}}
testSwear(nMs);}
function nameFem(){nTp=Math.random()*6|0;rnd=Math.random()*nm7.length|0;rnd2=Math.random()*nm8.length|0;rnd3=Math.random()*nm9.length|0;rnd4=Math.random()*nm10.length|0;rnd5=Math.random()*nm12.length|0;if(nTp<3){while(nm9[rnd3]===nm12[rnd5]||nm9[rnd3]===nm7[rnd]){rnd3=Math.random()*nm9.length|0;}
nMs=nm7[rnd]+nm8[rnd2]+nm9[rnd3]+nm10[rnd4]+nm12[rnd5];}else{rnd6=Math.random()*nm11.length|0;rnd7=Math.random()*nm8.length|0;while(nm12[rnd5]===nm11[rnd6]||nm11[rnd6]===nm9[rnd3]){rnd6=Math.random()*nm11.length|0;}
if(nTp<5){nMs=nm7[rnd]+nm8[rnd2]+nm9[rnd3]+nm8[rnd7]+nm11[rnd6]+nm10[rnd4]+nm12[rnd5];}else{rnd8=Math.random()*nm11.length|0;rnd9=Math.random()*nm8.length|0;while(nm12[rnd5]===nm11[rnd8]||nm11[rnd8]===nm11[rnd6]){rnd6=Math.random()*nm11.length|0;}
nMs=nm7[rnd]+nm8[rnd2]+nm9[rnd3]+nm8[rnd7]+nm11[rnd6]+nm8[rnd9]+nm11[rnd8]+nm10[rnd4]+nm12[rnd5];}}
testSwear(nMs);}