var nm1=["","","","b","br","d","dr","dh","g","gl","gh","gr","h","j","k","kr","kh","l","m","n","r","rh","v","vr","z","zr"];var nm2=["a","e","i","o","u","a","a","o","o","u","u","a","e","i","o","u","a","a","o","o","u","u","a","e","i","o","u","a","a","o","o","u","u","aa","au","uu","ou","ai","ia","oo","ua"];var nm3=["'r","'z","'zz","g","g'dr","gdr","gg","gr","gt","k","k'd","k'dr","kr","kd","l","l'dr","l'g","l'gr","l'r","ldr","lg","lgr","llm","lm","ln","lr","ldr","lv","lz","n","nd","ngr","nn","r","r'g","r'k","r'l","r'v","r'z","rb","rd","rg","rgr","rk","rk'l","rl","rn","rr","rz","tr","v","z","z'g","z'r","zg","zm","zr","zz"];var nm4=["a","e","i","o","u","a","a","o","o","u","u"];var nm6=["c","ch","d","g","gg","k","kk","l","m","n","r","rd","rg","s","z"];var nm7=["aberrant","acrid","agile","ancient","anger","arch","arid","bad","barren","beast","berserk","big","bite","bitter","black","blind","blood","bold","bone","bony","brash","brawn","breath","bright","burn","burst","chain","chaos","clear","clever","coal","coarse","coil","corrupt","craven","crazy","crimson","crooked","cruel","crush","dark","dead","death","demon","devil","dim","dirt","doom","draco","dragon","evil","faint","false","fear","feast","fire","flame","fluff","flux","forked","forsaken","fowl","froth","fuel","ghost","giant","gloom","glum","grand","grave","great","grim","half","harm","hate","haunt","heat","hell","hex","hollow","hook","horn","horror","hot","hunt","infernal","inferno","iron","keen","light","livid","lone","mad","melt","metal","molten","mute","night","nox","numb","odd","onyx","pale","parched","power","prime","putrid","quill","rabid","radiant","ragged","red","requiem","rot","rough","ruin","sanguine","scale","scorn","shade","shadow","sharp","shift","silent","smoke","smug","somber","soot","spite","stark","steam","stitch","storm","swift","temper","thermo","torn","twist","venom","vivid","volatile","warm","whip","wicked","wild","wrath"];var nm8=["band","bite","chomp","claw","claws","coat","collar","cub","fang","fangs","fur","hound","jaw","jaws","maw","mongrel","mutt","paw","paws","pelt","pooch","pup","sable","tail","teeth","tooth"];var br="";function nameGen(type){var tp=type;$('#placeholder').css('textTransform','capitalize');var element=document.createElement("div");element.setAttribute("id","result");for(i=0;i<10;i++){if(i<4){rnd=Math.random()*nm7.length|0;rnd2=Math.random()*nm8.length|0;while(nm7[rnd]===nm8[rnd]){rnd=Math.random()*nm7.length|0;}
nMs=nm7[rnd]+nm8[rnd2];}else{nameMas();while(nMs===""){nameMas();}}
br=document.createElement('br');element.appendChild(document.createTextNode(nMs));element.appendChild(br);}
if(document.getElementById("result")){document.getElementById("placeholder").removeChild(document.getElementById("result"));}
document.getElementById("placeholder").appendChild(element);}
function nameMas(){nTp=Math.random()*2|0;rnd=Math.random()*nm1.length|0;rnd2=Math.random()*nm2.length|0;rnd5=Math.random()*nm6.length|0;if(nTp===0){while(nm1[rnd]===""){rnd=Math.random()*nm1.length|0;}
while(nm6[rnd5]===nm1[rnd]){rnd5=Math.random()*nm6.length|0;}
nMs=nm1[rnd]+nm2[rnd2]+nm6[rnd5];}else{rnd3=Math.random()*nm3.length|0;rnd4=Math.random()*nm4.length|0;if(nTp<3){while(nm3[rnd3]===nm1[rnd]||nm3[rnd3]===nm6[rnd5]){rnd3=Math.random()*nm3.length|0;}
nMs=nm1[rnd]+nm4[rnd4]+nm3[rnd3]+nm2[rnd2]+nm6[rnd5];}}
testSwear(nMs);}