var nm1 = ["ABC","Aeos","Algorithm","Amenity","Angel's","Anomaly","Apex","Aptitude","Art Archive","Avant-garde","Beauview","Blossoms","Book Mark","Booked","Bookworm","Calligraph","Capitol","Carpe Librum","Celestial","Central Park","Chapter","Chapter One","Charity","Chimera","Codex","Compendium","Cosmic","Courtesy","Crescent Moon","Crest","Crossroad","Crown","Curio","Curiosity","Data","Daydream","Desire","Discovery","Divine","Epiphany","Epitome","Equinox","Estate","Eternal","Evening Hour","Explorer","Figment","First Story","Forte","Freedom","Frontier","Gift's","Global","Globe","Grand","Grand Archive","Grand Duchess","Grand Isle","Grand Monastery","Grand Oak","Grand State","Grotto","Guardian's","Harborview","Harmony","Heirloom","Heritage","Holy","Idle Hour","Illusions","Imagine","Imperial","Infinity","Innovation","Inquiry","Insight","Institute","Jubilee","King's","Knight","Knowledge","Labyrinth","Legacy","Leisure","Lexicon","Liberty","Lullaby","Marvel","Memorial","Millennium","Miracle","Mirage","Mystery","National History","National Memorial","National Public","National University","Novel Idea","Obelisk","Oceanic","Open Book","Opus","Oracle","Page One","Paragon","Patrimony","Pinnacle","Pioneer","Plainfield","Prime","Prism","Probe","Prodigy","Public Scientific","Pursuit","Quest","Quietus","Rainbow","Reader's Garden","Repose","Requiem","Reticence","Revelation","Reverie","Rising Sun","Royal","Saturninity","Savant","Scholar's","Serenity","Solace","Solitude","Spectrum","Spring Harbor","Stellar","Summit","Supreme","Tempest","Temple","Titlewave","Tranquility","Treatise","Trove","Utopia","Vade Mecum","Valley","Virtue","Vision","Wonder","Zenith"];
var nm2 = ["Library","Bibliotheca","Library","Library","Library","Library","Library","Library","Library","Library","Library","Athenaeum"];
var nm3 = ["Éternelle","Céleste","Commémorative","Cosmique","Divine","Donnée","Fondamentale","Globale","Grandiose","Illimitée","Immense","Impériale","Incroyable","Infinie","Magique","Magnifique","Mondiale","Mystérieuse","Noble","Océanique","Pélagique","Principale","Royale","Sacrée","Silencieuse","Stellaire","Suprême","Universelle","d'Épiphanies","d'Épitomes","d'Équinoxe","d'ABC","d'Algorithme","d'Aménité","d'Ange","d'Anomalie","d'Aptitude","d'Arc-en-Ciel","d'Archives d'Art","d'Art","d'Avantage","d'Enfants","d'Enfants Doués","d'Explorateurs","d'Héritage","d'Harmonie","d'Havre","d'Histoire Nationale","d'Idées","d'Illusions","d'Imagination","d'Infinité","d'Initiateur","d'Innovation","d'Invention","d'Investigation","d'Obélisque","d'Oopus","d'Oracle","de Beauté","de Berceuse","de Calligraphie","de Calme","de Charité","de Charme","de Chevalier","de Confort","de Connaissance","de Courtoisie","de Création","de Curio","de Curiosité","de Découverte","de Désir","de Fantaisie","de Fleurs","de Floraisons","de Fortune","de Gardien","de Jubilé","de Lecteurs","de Lexique","de Libération","de Liberté","de Loisir","de Lumière","de Mémoire","de Mérite","de Marque-Pages","de Merveilles","de Miracles","de Mirages","de Mystère","de Page Un","de Parangon","de Parc Central","de Patrimoine","de Perspicacité","de Pionnier","de Poursuite","de Prévoyance","de Prodige","de Quêtes","de Révélations","de Rêvasserie","de Rêverie","de Recherche","de Repos","de Sérénité","de Science","de Signets","de Silence","de Solitude","de Souvenir","de Stupeur","de Tempête","de Tranquillité","de Vertu","de Vision","de l'Île","de l'Ange","de la Chimère","de la Cime","de la Concorde","de la Couronne","de la Frontière","de la Grande Archive","de la Grande Duchesse","de la Grotte","de la Lune","de la Première Histoire","de la Reine","de la Terre","de la Vallée","des Aeons","des Données","des Idées Originales","des Lumières","des Rats","du Capitole","du Carrefour","du Chêne","du Chapitre Un","du Compendium","du Globe","du Jardin","du Labyrinthe","du Mémorial","du Mémorial National","du Manuscrit","du Millénium","du Pinacle","du Prisme","du Roi","du Soleil","du Soleil Levant","du Sommet","du Temple","du Zénith"];
var nm4 = ["Cósmica","Celeste","Celestial","Conmemorativa","Creciente","Divina","Estelar","Eterna","Global","Imperial","Infinita","Oceánica","Pionera","Real","Sabia","da la Dama","de Admiración","de Amenidad","de Aptitud","de Arco Iris","de Armonía","de Arte","de Búsqueda","de Beneficencia","de Bravura","de Caligrafía","de Capítulo Uno","de Capítulos","de Caridad","de Cenit","de Ciencia","de Comodidad","de Comprensión","de Conocimiento","de Consuelo","de Cortesía","de Curiosidad","de Curiosidades","de Descubrimiento","de Deseo","de Ensueño","de Epítome","de Erudición","de Exploración","de Facilidad","de Flores","de Gran Archivo","de Gran Duquesa","de Gran Roble","de Harmonía","de Herencia","de Historia","de Historia Nacional","de Imaginación","de Información","de Innovación","de Intuición","de Invención","de Inventiva","de Investigación","de Legado","de Libertad","de Maravilla","de Medialuna","de Milagro","de Misterio","de Novelas","de Ocio","de Pasatiempo","de Patrimonio","de Percepción","de Prodigio","de Propósito","de Réquiem","de Regalo","de Relato","de Reposo","de Reticencia","de Revelación","de Serenidad","de Siempre","de Simetría","de Soledad","de Supremo","de Unidad","de Urbanidad","de Utopía","de Valentía","de Virtud","de Visión","de la Anomalía","de la Cima","de la Corona","de la Cresta","de la Donación","de la Epifanía","de la Frontera","de la Gruta","de la Herencia","de la Quimera","de la Reliquia","de la Sonda","de la Vanguardia","de las Historias","de las Horas Ociosas","de los Ángeles","de los Enigmas","de los Eruditos","de los Espejismos","de los Exploradores","de los Milagros","de los Pioneros","de los Sabios","de los Tutores","del Ángel","del Ápex","del Algoritmo","del Aniversario","del Apogeo","del Códice","del Caballero","del Capitolio","del Epítome","del Equinoccio","del Estado","del Globo","del Guardián","del Infinito","del Instituto","del Léxico","del Laberinto","del Memorial","del Memorial Nacional","del Milenio","del Obelisco","del Opus","del Oráculo","del Patrimonio","del Pináculo","del Prisma","del Prodigio","del Protector","del Rey","del Templo","del Tratado","del Valle"];
var br = "";

function nameGen(type){
	var tp = type;
	var element = document.createElement("div");
	element.setAttribute("id", "result");
	
	for(i = 0; i < 10; i++){
		if(tp === 1){
			rnd = Math.random() * nm3.length | 0;
			names = "la Bibliothèque " + nm3[rnd];
		}else if(tp === 2){
			rnd = Math.random() * nm4.length | 0;
			names = "la Biblioteca " + nm4[rnd];
		}else{
			rnd = Math.random() * nm1.length | 0;
			rnd2 = Math.random() * nm2.length | 0;
			names = nm1[rnd] + " " + nm2[rnd2];
		}
		br = document.createElement('br');	
		element.appendChild(document.createTextNode(names));
		element.appendChild(br);
	}
	if(document.getElementById("result")){
		document.getElementById("placeholder").removeChild(document.getElementById("result"));
	}		
	document.getElementById("placeholder").appendChild(element);
}